theme: osuny
enableRobotsTXT: true
removePathAccents: true
pagination:
  pagerSize: 30
params:
  breadcrumb:
    position: after-hero
  summary:
    position: hero
  search:
    active: true
  logo:
    header: ''
    footer: ''
  posts:
    index:
      layout: grid
    share_links:
      enabled: true
      email: true
      facebook: false
      linkedin: true
      mastodon: true
      telegram: false
      twitter: false
      whatsapp: false