[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/actualites/2024-09-08-eduquer-au-numerique-sur-la-ligne-de-crete-entre-paniques-morales-et-technorassurisme/"
to = "/carnet/2024-09-08-eduquer-au-numerique-sur-la-ligne-de-crete-entre-paniques-morales-et-technorassurisme/"

[[redirects]]
from = "/louis-derrac/"
to = "/equipe/louis-derrac/"

[[redirects]]
from = "/louis-derrac/carnet/"
to = "/equipe/louis-derrac/carnet/"

[[redirects]]
from = "/actualites/"
to = "/carnet/"

[[redirects]]
from = "/actualites/2024-09-08-eduquer-au-numerique-dans-la-ligne-de-crete-entre-paniques-morales-et-technorassurisme/"
to = "/carnet/2024-09-08-eduquer-au-numerique-sur-la-ligne-de-crete-entre-paniques-morales-et-technorassurisme/"

